apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: sonarqube-scan
spec:
  params:
    - name: sonar-project-key
      type: string
    - description: Kubernetes secrets contain image push username and password
      name: SONARQUBE_SECRET_NAME
      type: string
  steps:
    - computeResources: {}
      env:
        - name: LOGIN
          valueFrom:
            secretKeyRef:
              key: login
              name: $(params.SONARQUBE_SECRET_NAME)
        - name: HOSTURL
          valueFrom:
            secretKeyRef:
              key: hosturl
              name: $(params.SONARQUBE_SECRET_NAME)
      image: sonarsource/sonar-scanner-cli
      name: sonarqube-scan
      script: |
        sonar-scanner \
          -Dsonar.projectKey=$(params.sonar-project-key) \
          -Dsonar.sources=. \
          -Dsonar.host.url=${HOSTURL} \
          -Dsonar.login=${LOGIN}
