apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-deployment
spec:
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
      - name: employee
        image: rosewei/employee-service:1.0
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: employee-service
spec:
  type: ClusterIP
  selector:
    app: employee
  ports:
  - port: 8080
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: employee-service
  labels:
    app: employee-service
    app.kubernetes.io/component: employee-service
    app.kubernetes.io/instance: employee-service
spec:
  to:
    kind: Service
    name: employee-service
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
